# What is NumPy?


NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

Core of the NumPy package, is the ndarray object.



In [1]:
import numpy as np

In [2]:
a = np.arange(15).reshape(3, 5)

In [3]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [4]:
a.shape

(3, 5)

In [5]:
a.ndim

2

In [6]:
a.dtype.name

'int32'

In [8]:
a.itemsize

4

In [9]:
a.size

15

In [10]:
type(a)

numpy.ndarray

In [11]:
b = np.array([6, 7, 8])

In [14]:
type(b)

numpy.ndarray

In [15]:
b = np.array([1.2, 3.5, 5.1])

In [16]:
b.dtype

dtype('float64')

In [17]:
b = np.array([(1.5, 2, 3), (4, 5, 6)])

In [18]:
b.dtype

dtype('float64')

In [19]:
c = np.array([[1, 2], [3, 4]], dtype=complex)

In [20]:
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [21]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
np.arange(10, 30, 5)

array([10, 15, 20, 25])

In [23]:
np.arange(0, 2, 0.3) 

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [24]:
from numpy import pi

In [25]:
np.linspace(0, 2, 9) 

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [26]:
 from numpy import pi

In [73]:
x = np.linspace(0, pi, 100)  

In [74]:
x

array([0.        , 0.03173326, 0.06346652, 0.09519978, 0.12693304,
       0.1586663 , 0.19039955, 0.22213281, 0.25386607, 0.28559933,
       0.31733259, 0.34906585, 0.38079911, 0.41253237, 0.44426563,
       0.47599889, 0.50773215, 0.53946541, 0.57119866, 0.60293192,
       0.63466518, 0.66639844, 0.6981317 , 0.72986496, 0.76159822,
       0.79333148, 0.82506474, 0.856798  , 0.88853126, 0.92026451,
       0.95199777, 0.98373103, 1.01546429, 1.04719755, 1.07893081,
       1.11066407, 1.14239733, 1.17413059, 1.20586385, 1.23759711,
       1.26933037, 1.30106362, 1.33279688, 1.36453014, 1.3962634 ,
       1.42799666, 1.45972992, 1.49146318, 1.52319644, 1.5549297 ,
       1.58666296, 1.61839622, 1.65012947, 1.68186273, 1.71359599,
       1.74532925, 1.77706251, 1.80879577, 1.84052903, 1.87226229,
       1.90399555, 1.93572881, 1.96746207, 1.99919533, 2.03092858,
       2.06266184, 2.0943951 , 2.12612836, 2.15786162, 2.18959488,
       2.22132814, 2.2530614 , 2.28479466, 2.31652792, 2.34826

In [29]:
a = np.arange(6) 

In [31]:
print(a)

[0 1 2 3 4 5]


In [32]:
a = np.arange(6).reshape(2,3)

In [63]:
a

array([[5., 9., 1., 9.],
       [3., 4., 8., 4.],
       [5., 0., 7., 5.]])

In [34]:
 a = np.array([20, 30, 40, 50])

In [35]:
b = np.arange(4)

In [36]:
c = a - b

In [109]:
c

array([[1., 5., 7., 2., 7., 5., 1., 9., 4., 2., 8., 1.],
       [7., 1., 3., 2., 8., 3., 9., 6., 6., 5., 3., 3.]])

In [38]:
b**2

array([0, 1, 4, 9], dtype=int32)

In [39]:
10 * np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [43]:
rg = np.random.default_rng(1)
a = np.floor(10 * rg.random((3, 4)))
a

array([[5., 9., 1., 9.],
       [3., 4., 8., 4.],
       [5., 0., 7., 5.]])

# Matrix Operations

In [44]:
 A = np.array([[1, 1], [0, 1]])

In [45]:
A

array([[1, 1],
       [0, 1]])

In [46]:
B = np.array([[2, 0],[3, 4]])


In [47]:
B

array([[2, 0],
       [3, 4]])

In [48]:
A@B

array([[5, 4],
       [3, 4]])

In [69]:
 b = rg.random((2, 3))

In [70]:
b

array([[0.81962672, 0.68328691, 0.78709694],
       [0.19161626, 0.80236416, 0.19132393]])

In [67]:
a = np.ones((2, 3), dtype=int)

In [68]:
a

array([[1, 1, 1],
       [1, 1, 1]])

In [71]:
b += a

In [72]:
b

array([[1.81962672, 1.68328691, 1.78709694],
       [1.19161626, 1.80236416, 1.19132393]])

In [75]:
a = np.arange(10)**3

In [76]:
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [77]:
a[2:5]

array([ 8, 27, 64], dtype=int32)

In [78]:
a[:6:2] = 1000

In [79]:
a

array([1000,    1, 1000,   27, 1000,  125,  216,  343,  512,  729],
      dtype=int32)

In [82]:
y=rg.random((2, 2))

In [83]:
y

array([[0.08155262, 0.85522697],
       [0.8612835 , 0.8765371 ]])

In [85]:
np.floor(10*y)

array([[0., 8.],
       [8., 8.]])

In [88]:
a = np.floor(10 * rg.random((2, 2)))

In [89]:
a

array([[7., 8.],
       [2., 2.]])

In [90]:
b = np.floor(10 * rg.random((2, 2)))

In [91]:
b

array([[6., 8.],
       [9., 1.]])

In [93]:
np.vstack((a,b))

array([[7., 8.],
       [2., 2.],
       [6., 8.],
       [9., 1.]])

In [94]:
np.hstack((a,b))

array([[7., 8., 6., 8.],
       [2., 2., 9., 1.]])

In [102]:
a = np.floor(10 * rg.random((2, 12)))
a

array([[1., 5., 7., 2., 7., 5., 1., 9., 4., 2., 8., 1.],
       [7., 1., 3., 2., 8., 3., 9., 6., 6., 5., 3., 3.]])

In [103]:
 # Split `a` into 3
np.hsplit(a, 3)

[array([[1., 5., 7., 2.],
        [7., 1., 3., 2.]]),
 array([[7., 5., 1., 9.],
        [8., 3., 9., 6.]]),
 array([[4., 2., 8., 1.],
        [6., 5., 3., 3.]])]

In [104]:
 # Split `a` after the third and the fourth column
np.hsplit(a, (3, 4))

[array([[1., 5., 7.],
        [7., 1., 3.]]),
 array([[2.],
        [2.]]),
 array([[7., 5., 1., 9., 4., 2., 8., 1.],
        [8., 3., 9., 6., 6., 5., 3., 3.]])]

In [111]:
#View or Shallow Copy
c = a.view()
c is a

False

In [112]:
 c.base is a

True

In [113]:
 c.flags.owndata

False

In [114]:
c = c.reshape((4, 6))

In [115]:
c

array([[1., 5., 7., 2., 7., 5.],
       [1., 9., 4., 2., 8., 1.],
       [7., 1., 3., 2., 8., 3.],
       [9., 6., 6., 5., 3., 3.]])

In [116]:
a.shape

(2, 12)

In [117]:
c[0, 4] = 1234 

In [118]:
a

array([[1.000e+00, 5.000e+00, 7.000e+00, 2.000e+00, 1.234e+03, 5.000e+00,
        1.000e+00, 9.000e+00, 4.000e+00, 2.000e+00, 8.000e+00, 1.000e+00],
       [7.000e+00, 1.000e+00, 3.000e+00, 2.000e+00, 8.000e+00, 3.000e+00,
        9.000e+00, 6.000e+00, 6.000e+00, 5.000e+00, 3.000e+00, 3.000e+00]])

In [119]:
c

array([[1.000e+00, 5.000e+00, 7.000e+00, 2.000e+00, 1.234e+03, 5.000e+00],
       [1.000e+00, 9.000e+00, 4.000e+00, 2.000e+00, 8.000e+00, 1.000e+00],
       [7.000e+00, 1.000e+00, 3.000e+00, 2.000e+00, 8.000e+00, 3.000e+00],
       [9.000e+00, 6.000e+00, 6.000e+00, 5.000e+00, 3.000e+00, 3.000e+00]])

In [120]:
s = a[:, 1:3]

In [121]:
s

array([[5., 7.],
       [1., 3.]])

In [122]:
#Deep Copy

In [123]:
d = a.copy() 

In [124]:
d is a

False

In [125]:
d.base is a

False

In [126]:
d[0, 0] = 9999

In [127]:
a

array([[1.000e+00, 5.000e+00, 7.000e+00, 2.000e+00, 1.234e+03, 5.000e+00,
        1.000e+00, 9.000e+00, 4.000e+00, 2.000e+00, 8.000e+00, 1.000e+00],
       [7.000e+00, 1.000e+00, 3.000e+00, 2.000e+00, 8.000e+00, 3.000e+00,
        9.000e+00, 6.000e+00, 6.000e+00, 5.000e+00, 3.000e+00, 3.000e+00]])

In [128]:
d

array([[9.999e+03, 5.000e+00, 7.000e+00, 2.000e+00, 1.234e+03, 5.000e+00,
        1.000e+00, 9.000e+00, 4.000e+00, 2.000e+00, 8.000e+00, 1.000e+00],
       [7.000e+00, 1.000e+00, 3.000e+00, 2.000e+00, 8.000e+00, 3.000e+00,
        9.000e+00, 6.000e+00, 6.000e+00, 5.000e+00, 3.000e+00, 3.000e+00]])

In [133]:
import numpy as np
rg = np.random.default_rng(1)
import matplotlib.pyplot as plt
# Build a vector of 10000 normal deviates with variance 0.5^2 and mean 2
mu, sigma = 2, 0.5
v = rg.normal(mu, sigma, 10000)
# Plot a normalized histogram with 50 bins
#plt.hist(v, bins=50, density=True)       # matplotlib version (plot)
# Compute the histogram with numpy and then plot it
(n, bins) = np.histogram(v, bins=50, density=True)  # NumPy version (no plot)
plt.plot(.5 * (bins[1:] + bins[:-1]), n)